on:
    push:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'npm'

            - name: Instal dependencies
              run: npm ci

            - name: Run Lint
              run: npm run lint

            - name: Run Unit Tests
              run: npm run test

    build-and-push:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push Backend
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile.backend
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-backend:latest
            
            - name: Build and Push Frontend
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile.frontend
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-frontend:latest
    
    deploy:
        needs: build-and-push
        runs-on: self-hosted
        steps:
              - name: Checkout code
                run: |
                    cd /var/www/myapp
                    git reset --hard
                    git fetch origin main
                    git reset --hard origin/main

              - name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

              - name: Build and Restart Containers
                run: |
                    cd /var/www/myapp
                    docker compose down
                    docker compose pull
                    docker compose up -d
                    docker image prune -f